name: Terraform Lint and Security Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-security:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'  # or whichever version you prefer

      - name: Make lint script executable
        run: chmod +x shell_scripts/lint.sh

      - name: Run lint and security checks
        run: shell_scripts/lint.sh